### ISSUE TITLE
ConsumerWorker WakeupException

### ISSUE THREAD

**Issue by praveenkanamarlapudi** [BigDataDevs/kafka-elasticsearch-consumer#106]
While starting the app, we are seeing the below error. Can you help us with it?

```
> 2020-01-23 23:17:29:153 [kafka-consumer-thread-9] WARN  o.e.k.indexer.jobs.ConsumerWorker - ConsumerWorker [consumerInstanceId=9] got WakeupException - exiting ...
> org.apache.kafka.common.errors.WakeupException: null
>         at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.maybeTriggerWakeup(ConsumerNetworkClient.java:487)
>         at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:278)
>         at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:236)
>         at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:215)
>         at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.joinGroupIfNeeded(AbstractCoordinator.java:401)
>         at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureActiveGroup(AbstractCoordinator.java:344)
>         at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:342)
>         at org.apache.kafka.clients.consumer.KafkaConsumer.updateAssignmentMetadataIfNeeded(KafkaConsumer.java:1226)
>         at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1191)
>         at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1176)
>         at org.elasticsearch.kafka.indexer.jobs.ConsumerWorker.processPoll(ConsumerWorker.java:117)
>         at org.elasticsearch.kafka.indexer.jobs.ConsumerWorker.run(ConsumerWorker.java:92)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
>         at java.lang.Thread.run(Thread.java:745)
> 2020-01-23 23:17:29:153 [kafka-consumer-thread-9] WARN  o.e.k.indexer.jobs.ConsumerWorker - ConsumerWorker [consumerInstanceId=9] is shutting down ...
```

**Comment by merlin-zaraza** [comment]
@praveenkanamarlapudi could you please describe how do you run app? what did you change in config, etc.?

**Comment by praveenkanamarlapudi** [comment]
Please ignore. I rebuild the jars by changing the kafka version to `2.2.1` and is working as expected.
