### ISSUE TITLE
 Error posting messages to ElasticSearch: NoNodeAvailableException - ES cluster is unreachable, will try to re-connect after sleeping ..

### ISSUE THREAD

**Issue by zousheng** [BigDataDevs/kafka-elasticsearch-consumer#41]
Hi,

This verson has issues during initialization, it failed to post messsage to es cluster, the error is as below:

I checked the ES cluster, the state is greeen and healthy

app error:
2016-07-03 07:29:23:576 [kafka-es-indexer-thread-1] INFO  o.e.kafka.indexer.jobs.IndexerJob - About to post messages to ElasticSearch for partition=1, offsets 591509-->600397
2016-07-03 07:29:23:577 [kafka-es-indexer-thread-1] ERROR o.e.k.i.s.ElasticSearchBatchService - Error posting messages to ElasticSearch: NoNodeAvailableException - ES cluster is unreachable, will try to re-connect after sleeping ...
org.elasticsearch.client.transport.NoNodeAvailableException: None of the configured nodes are available: []
        at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:305) ~[elasticsearch-1.5.2.jar:na]
        at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:200) ~[elasticsearch-1.5.2.jar:na]
        at org.elasticsearch.client.transport.support.InternalTransportClient.execute(InternalTransportClient.java:106) ~[elasticsearch-1.5.2.jar:na]
        at org.elasticsearch.client.support.AbstractClient.bulk(AbstractClient.java:163) ~[elasticsearch-1.5.2.jar:na]
        at org.elasticsearch.client.transport.TransportClient.bulk(TransportClient.java:356) ~[elasticsearch-1.5.2.jar:na]
        at org.elasticsearch.action.bulk.BulkRequestBuilder.doExecute(BulkRequestBuilder.java:164) ~[elasticsearch-1.5.2.jar:na]
        at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:91) ~[elasticsearch-1.5.2.jar:na]
        at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:65) ~[elasticsearch-1.5.2.jar:na]
        at org.elasticsearch.kafka.indexer.service.ElasticSearchBatchService.postBulkToEs(ElasticSearchBatchService.java:95) [main/:na]
        at org.elasticsearch.kafka.indexer.service.ElasticSearchBatchService.postToElasticSearch(ElasticSearchBatchService.java:58) [main/:na]
        at org.elasticsearch.kafka.indexer.service.impl.examples.SimpleMessageHandlerImpl.postToElasticSearch(SimpleMessageHandlerImpl.java:43) [main/:na]
        at org.elasticsearch.kafka.indexer.jobs.IndexerJob.postBatchToElasticSearch(IndexerJob.java:187) [main/:na]
        at org.elasticsearch.kafka.indexer.jobs.IndexerJob.processMessagesFromKafka(IndexerJob.java:136) [main/:na]
        at org.elasticsearch.kafka.indexer.jobs.IndexerJob.call(IndexerJob.java:70) [main/:na]
        at org.elasticsearch.kafka.indexer.jobs.IndexerJob.call(IndexerJob.java:22) [main/:na]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_40]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_40]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_40]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_40](END) 

es error:

[2016-07-03 15:23:59,940][WARN ][transport.netty          ] [Super-Nova] exception caught on transport layer [[id: 0x236001c0, /10.117.1.156:63574 => /10.117.11.185:9300]], closing connection
java.lang.IllegalStateException: Message not fully read (request) for requestId [101], action [cluster/nodes/info], readerIndex [39] vs expected [57]; resetting
        at org.elasticsearch.transport.netty.MessageChannelHandler.messageReceived(MessageChannelHandler.java:120)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
        at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:462)
        at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:443)
        at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.elasticsearch.common.netty.OpenChannelsHandler.handleUpstream(OpenChannelsHandler.java:75)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
        at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
        at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)

**Comment by ppine7** [comment]
The error you are getting suggests that there is a connectivity issue between your client (indexer) and the ES cluster - networking or permissions , most likely.
Make sure all ES ports are reachable from your client (you could use the 'nc -vz hostIP:port' command, for example)

thanks,
Marina

**Comment by znoodl** [comment]
Hi,
I also get this error, the es cluster is ok too,  have you solve this problem now?

**Comment by ppine7** [comment]
closing due to inactivity
