### ISSUE TITLE
Unable to load indexer.properties

### ISSUE THREAD

**Issue by inv-sgr** [BigDataDevs/kafka-elasticsearch-consumer#86]
I'm having what I deem to be a very basic issue. When attempting to run the built consumer with configuration files explicitly stated as options, I get the below failure:

`./kafka-elasticsearch-consumer -Dindexer.properties=/etc/kafka-elasticsearch-consumer/kafka-es-indexer.properties -Dlogback.configuration=/etc/kafka-elasticsearch-consumer/logback.xml`

`15:09:38.715 [main] DEBUG org.springframework.core.env.PropertySourcesPropertyResolver - Could not find key 'indexer.properties' in any property source
15:09:38.716 [main] DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Invoking afterPropertiesSet() on bean with name 'applicationProperties'
15:09:38.716 [main] DEBUG org.springframework.beans.factory.config.PropertiesFactoryBean - Loading properties file from class path resource [config/kafka-es-indexer.properties]
15:09:38.716 [main] INFO org.springframework.beans.factory.config.PropertiesFactoryBean - Properties resource not found: class path resource [config/kafka-es-indexer.properties] cannot be opened because it does not exist
15:09:38.716 [main] DEBUG org.springframework.beans.factory.config.PropertiesFactoryBean - Loading properties file from URL [file:${indexer.properties}]
15:09:38.716 [main] INFO org.springframework.beans.factory.config.PropertiesFactoryBean - Properties resource not found: ${indexer.properties} (No such file or directory)
15:09:38.717 [main] DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Finished creating instance of bean 'applicationProperties'
15:09:38.720 [main] DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Finished creating instance of bean 'org.springframework.context.support.PropertySourcesPlaceholderConfigurer#0'
15:09:38.721 [main] DEBUG org.springframework.core.env.MutablePropertySources - Adding [environmentProperties] PropertySource with lowest search precedence
15:09:38.721 [main] DEBUG org.springframework.core.env.MutablePropertySources - Adding [localProperties] PropertySource with lowest search precedence
15:09:38.722 [main] DEBUG org.springframework.core.env.PropertySourcesPropertyResolver - Could not find key 'indexer.properties' in any property source
15:09:38.722 [main] DEBUG org.springframework.core.env.PropertySourcesPropertyResolver - Could not find key 'indexer.properties' in any property source
15:09:38.723 [main] WARN org.springframework.context.support.ClassPathXmlApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanDefinitionStoreException: Invalid bean definition with name 'applicationProperties' defined in null: Could not resolve placeholder 'indexer.properties' in value " file:${indexer.properties}"; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'indexer.properties' in value " file:${indexer.properties}"
15:09:38.723 [main] DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Destroying singletons in org.springframework.beans.factory.support.DefaultListableBeanFactory@711f39f9: defining beans [elasticSearchClientService,elasticSearchBatchService,org.springframework.context.annotation.internalConfigurationAnnotationProcessor,org.springframework.context.annotation.internalAutowiredAnnotationProcessor,org.springframework.context.annotation.internalRequiredAnnotationProcessor,org.springframework.context.annotation.internalCommonAnnotationProcessor,org.springframework.context.event.internalEventListenerProcessor,org.springframework.context.event.internalEventListenerFactory,applicationProperties,org.springframework.context.support.PropertySourcesPlaceholderConfigurer#0,messageHandler,kafkaESConsumerManager]; root of factory hierarchy
Exception in thread "main" org.springframework.beans.factory.BeanDefinitionStoreException: Invalid bean definition with name 'applicationProperties' defined in null: Could not resolve placeholder 'indexer.properties' in value " file:${indexer.properties}"; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'indexer.properties' in value " file:${indexer.properties}"
        at org.springframework.beans.factory.config.PlaceholderConfigurerSupport.doProcessProperties(PlaceholderConfigurerSupport.java:223)
        at org.springframework.context.support.PropertySourcesPlaceholderConfigurer.processProperties(PropertySourcesPlaceholderConfigurer.java:180)
        at org.springframework.context.support.PropertySourcesPlaceholderConfigurer.postProcessBeanFactory(PropertySourcesPlaceholderConfigurer.java:152)
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:281)
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:161)
        at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:686)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:524)
        at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:139)
        at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:83)
        at org.elasticsearch.kafka.indexer.KafkaESIndexerProcess.main(KafkaESIndexerProcess.java:14)
Caused by: java.lang.IllegalArgumentException: Could not resolve placeholder 'indexer.properties' in value " file:${indexer.properties}"
        at org.springframework.util.PropertyPlaceholderHelper.parseStringValue(PropertyPlaceholderHelper.java:174)
        at org.springframework.util.PropertyPlaceholderHelper.replacePlaceholders(PropertyPlaceholderHelper.java:126)
        at org.springframework.core.env.AbstractPropertyResolver.doResolvePlaceholders(AbstractPropertyResolver.java:236)
        at org.springframework.core.env.AbstractPropertyResolver.resolveRequiredPlaceholders(AbstractPropertyResolver.java:210)
        at org.springframework.context.support.PropertySourcesPlaceholderConfigurer$2.resolveStringValue(PropertySourcesPlaceholderConfigurer.java:172)
        at org.springframework.beans.factory.config.BeanDefinitionVisitor.resolveStringValue(BeanDefinitionVisitor.java:282)
        at org.springframework.beans.factory.config.BeanDefinitionVisitor.resolveValue(BeanDefinitionVisitor.java:209)
        at org.springframework.beans.factory.config.BeanDefinitionVisitor.visitArray(BeanDefinitionVisitor.java:217)
        at org.springframework.beans.factory.config.BeanDefinitionVisitor.resolveValue(BeanDefinitionVisitor.java:189)
        at org.springframework.beans.factory.config.BeanDefinitionVisitor.visitPropertyValues(BeanDefinitionVisitor.java:141)
        at org.springframework.beans.factory.config.BeanDefinitionVisitor.visitBeanDefinition(BeanDefinitionVisitor.java:82)
        at org.springframework.beans.factory.config.PlaceholderConfigurerSupport.doProcessProperties(PlaceholderConfigurerSupport.java:220)
`

What am I missing? Why are my command line arguments being ignored?

**Comment by merlin-zaraza** [comment]
Hi @invinsec-sgregory 
README is not up to date. You have to set `JAVA_OPTS` or `KAFKA_ELASTICSEARCH_CONSUMER_OPTS` environment variable like:

`export KAFKA_ELASTICSEARCH_CONSUMER_OPTS="-Dindexer.properties=/etc/kafka-elasticsearch-consumer/kafka-es-indexer.properties -Dlogback.configuration=/etc/kafka-elasticsearch-consumer/logback.xml"`

The you can run `./kafka-elasticsearch-consumer`
